#!/bin/sh
# Installs QUADStor modules and userland programs on an end user system
# Copyright (C) QUADStor Systems
set -x
buildtype=$1

buildroot=`pwd`
export QUADSTOR_ROOT="$buildroot"
export PATH="/sbin:/usr/sbin:$PATH"
checkerror() {
	if [ "$?" != "0" ]; then
		exit 1
	fi
}

checkprog() {
	found=`which $1`
	if [ "$found" = "" ]; then
		echo "ERROR: $1 needs to be installed"
		exit 1
	fi
}

os=`uname`
GMAKE="make"
if [ "$os" = "FreeBSD" ]; then
	GMAKE="gmake"
fi

coreversion=""
itfversion=""
if [ "$os" = "FreeBSD" ]; then
	coreversion=`pkg_info | grep quadstor-vtl-core`
	itfversion=`pkg_info | grep quadstor-vtl-itf`
else
	dpkgexists=`which dpkg`
	if [ "$dpkgexists" != "" ]; then
		coreversion=`dpkg --get-selections | grep quadstor-vtl-core | grep -v purge | grep -v deinstall`
		itfversion=`dpkg --get-selections | grep quadstor-vtl-itf | grep -v purge | grep -v deinstall`
	else
		coreversion=`rpm -qa | grep quadstor-vtl-core`
		itfversion=`rpm -qa | grep quadstor-vtl-itf`
	fi
fi
if [ "$coreversion" != "" ]; then
	echo "quadstor-vtl-core package needs to be uninstalled first"
	exit 1
fi
if [ "$itfversion" != "" ]; then
	echo "quadstor-vtl-itf package needs to be uninstalled first"
	exit 1
fi

checkprog $GMAKE
checkprog make
checkprog sudo
checkprog install 

rm $QUADSTOR_ROOT/target-mode/fc/isp
rm $QUADSTOR_ROOT/target-mode/fc/qla2xxx
cd $QUADSTOR_ROOT/build && sh buildinit.sh $buildtype && cd $QUADSTOR_ROOT
checkerror

sh buildworld clean
checkerror
if [ "$buildtype" = "rhel6x86" ]; then
	sh buildworld x86
else
	sh buildworld
fi
checkerror
sh buildworld install
checkerror

cd $QUADSTOR_ROOT/pgsql && sudo $GMAKE install DESTDIR=/ && cd $QUADSTOR_ROOT
sudo install -m 755 -d /quadstorvtl/lib/modules
sudo install -m 755 -d /quadstorvtl/bin
sudo install -m 755 -d /quadstorvtl/sbin
sudo install -m 755 -d /quadstorvtl/lib
sudo install -m 755 -d /quadstorvtl/lib/modules
sudo install -m 755 -d /quadstorvtl/etc
sudo install -m 755 -d /quadstorvtl/etc/iet

sudo install -m 644  $QUADSTOR_ROOT/library/client/libtlclnt.so /quadstorvtl/lib/libtlclnt.so
sudo install -m 644 $QUADSTOR_ROOT/library/server/libtlsrv.so /quadstorvtl/lib/libtlsrv.so
sudo install -m 644 $QUADSTOR_ROOT/library/common/libtlmsg.so /quadstorvtl/lib/libtlmsg.so
sudo install -m 755 $QUADSTOR_ROOT/sbin/vtmdaemon /quadstorvtl/sbin/
sudo install -m 755 $QUADSTOR_ROOT/sbin/ietd /quadstorvtl/sbin/
sudo install -m 755 $QUADSTOR_ROOT/bin/* /quadstorvtl/bin/

if [ "$os" = "FreeBSD" ]; then
	sudo mkdir -p /quadstorvtl/lib/modules
	sudo install -m 755 $QUADSTOR_ROOT/export/*.ko /quadstorvtl/lib/modules/
	sudo install -m 755 $QUADSTOR_ROOT/target-mode/fc/isp/ispmod.ko /boot/kernel/
	sudo install -m 755 $QUADSTOR_ROOT/target-mode/iscsi/kernel/iscsit.ko /quadstorvtl/lib/modules/
	sudo install -m 755 $QUADSTOR_ROOT/etc/quadstor /etc/rc.d/quadstorvtl
else
	kvers=`uname -r`
	sudo install -m 755 -d /quadstorvtl/lib/modules/$kvers
	sudo install -m 755 $QUADSTOR_ROOT/target-mode/iscsi/kernel/iscsit.ko /quadstorvtl/lib/modules/$kvers/
	sudo install -m 755 $QUADSTOR_ROOT/export/*.ko /quadstorvtl/lib/modules/$kvers/
	sudo install -m 755 $QUADSTOR_ROOT/target-mode/fc/qla2xxx/qla2xxx.ko /quadstorvtl/lib/modules/$kvers/
	if [ -f $QUADSTOR_ROOT/target-mode/fc/srpt/ib_srpt.ko ]; then
		sudo install -m 755 $QUADSTOR_ROOT/target-mode/fc/srpt/ib_srpt.ko /quadstorvtl/lib/modules/$kvers/
	fi
	chmod +x $QUADSTOR_ROOT/scripts/qlainst
	sudo $QUADSTOR_ROOT/scripts/qlainst
	if [ -d /etc/rc.d/init.d ]; then
		sudo install -m 755 $QUADSTOR_ROOT/etc/quadstor.linux /etc/rc.d/init.d/quadstorvtl
		sudo /sbin/chkconfig --add quadstorvtl
	elif [ -d /etc/rc.d ]; then
		sudo install -m 755 $QUADSTOR_ROOT/etc/quadstor.linux /etc/rc.d/quadstorvtl
		sudo /sbin/chkconfig --add quadstorvtl
	else
		sudo install -m 755 $QUADSTOR_ROOT/etc/quadstor.linux /etc/init.d/quadstorvtl
		sudo sed -e 's/# Default-Start:.*/# Default-Start:\t\t2 3 4 5/g' -i /etc/init.d/quadstorvtl
		sudo sed -e 's/# Default-Stop:.*/# Default-Stop:\t\t\t0 1 6/g' -i /etc/init.d/quadstorvtl
		sudo update-rc.d quadstorvtl defaults
	fi
fi

datacontents=`sudo ls /quadstorvtl/pgsql/data`
if [ "$datacontents" = "" ]; then
	sudo /quadstorvtl/pgsql/scripts/pgpost.sh
fi
sudo /quadstorvtl/pgsql/scripts/pgpatch.sh

sudo install -m 755 $QUADSTOR_ROOT/target-mode/iscsi/etc/targets.allow $RPM_BUILD_ROOT/quadstorvtl/etc/iet/targets.allow.sample
sudo install -m 755 $QUADSTOR_ROOT/target-mode/iscsi/etc/initiators.allow $RPM_BUILD_ROOT/quadstorvtl/etc/iet/initiators.allow.sample
sudo install -m 755 $QUADSTOR_ROOT/target-mode/iscsi/etc/ietd.conf $RPM_BUILD_ROOT/quadstorvtl/etc/iet/ietd.conf.sample
if [ ! -f /quadstorvtl/etc/iet/targets.allow ]; then
	cp /quadstorvtl/etc/iet/targets.allow.sample /quadstorvtl/etc/iet/targets.allow
fi

if [ ! -f /quadstorvtl/etc/iet/initiators.allow ]; then
	cp /quadstorvtl/etc/iet/initiators.allow.sample /quadstorvtl/etc/iet/initiators.allow
fi

if [ ! -f /quadstorvtl/etc/iet/ietd.conf ]; then
	cp /quadstorvtl/etc/iet/ietd.conf.sample /quadstorvtl/etc/iet/ietd.conf
fi


if [ -d /usr/local/www/apache22/ ]; then 
	htdocs=/usr/local/www/apache22/data;
	cgibin=/usr/local/www/apache22/cgi-bin;
elif [ -d /usr/local/www/ ]; then
	htdocs=/usr/local/www/data;
	cgibin=//usr/local/www/cgi-bin;
elif [ -f /etc/debian_version ]; then
	htdocs="/var/www"
	cgibin="/usr/lib/cgi-bin"
elif [ -f /etc/SuSE-release ]; then
	htdocs="/srv/www/htdocs"
	cgibin="/srv/www/cgi-bin"
elif [ -f /etc/redhat-release ]; then
	htdocs=/var/www/html
	cgibin=/var/www/cgi-bin
else
	htdocs="/var/www"
	cgibin="/usr/lib/cgi-bin"
fi

sudo mkdir -p $htdocs/quadstor
if [ ! -d $htdocs/quadstorvtl/yui ]; then
	sudo cp -r $QUADSTOR_ROOT/httpd/www/quadstorvtl/yui $htdocs/quadstorvtl/
fi

sudo cp -f $QUADSTOR_ROOT/httpd/www/quadstorvtl/*.js $htdocs/quadstorvtl
sudo cp -f $QUADSTOR_ROOT/httpd/www/quadstorvtl/*.css $htdocs/quadstorvtl
sudo cp -f $QUADSTOR_ROOT/httpd/www/quadstorvtl/*.png $htdocs/quadstorvtl
if [ -f $htdocs/index.html ]; then
	sudo mv -f $htdocs/index.html $htdocs/index.html.qsave
fi
sudo cp -f $QUADSTOR_ROOT/httpd/www/vtindex.html $htdocs/index.html
