#!/bin/sh
#
# QUADStor init script 
# chkconfig: 345 84 16
# description: QUADStor Data Protection 
#

# PROVIDE: quadstorvtl
# REQUIRE: DAEMON HOSTNAME mountcritlocal NETWORK quadstor
# KEYWORD: nojail shutdown

. /etc/rc.subr
name="quadstorvtl"
start_cmd="quadstorvtl_start"
stop_cmd="quadstorvtl_stop"
status_cmd="quadstorvtl_status"
rcvar=`set_rcvar`

unload_module() {
	/sbin/kldunload $1 > /dev/null 2>&1
	modpresent=`/sbin/kldstat | grep $1`
	tries="0"
	while [ "$modpresent" != "" ]; do
		sleep .1
		/sbin/kldunload $1 > /dev/null 2>&1
		if [ "$tries" = "50" ]; then
			break
		fi
		tries=`expr $tries + 1`
		modpresent=`/sbin/kldstat | grep $1`
	done
}

kill_prog() {
	pkill -f $1
	progpid=`quadstorvtl/bin/pidof $1 2> /dev/null`
	tries="0"
	while [ "$progpid" != "" ]; do
		sleep .1
		if [ "$tries" = "50" ]; then
			break
		fi
		tries=`expr $tries + 1`
		progpid=`quadstorvtl/bin/pidof $1 2> /dev/null`
	done
}

quadstorvtl_stop() {
	if [ -f /quadstorvtl/quadstor.lock ]; then
		echo "Waiting 60 seconds for lock"
		sleep 60
	fi

	touch /quadstorvtl/quadstor.lock

	/quadstorvtl/bin/ietadm --op delete >/dev/null 2>/dev/null
	kill_prog "/quadstorvtl/sbin/ietd"

	echo -n $"Stopping $prog: "
	/quadstorvtl/bin/scctl -u > /dev/null 2>&1

	kill_prog "/quadstorvtl/sbin/vtmdaemon"
	rm -f /quadstorvtl/.vtmdaemon

	/quadstorvtl/pgsql/etc/pgsql stop

	unload_module "iscsit"
	unload_module "vtldev"
	unload_module "vtlcore"
	rm -f /tmp/.quadstortl.* > /dev/null 2>&1
	rm -f /quadstorvtl/quadstor.lock
}

check_error() {
	if [ "$?" != "0" ]; then
		echo "$1"
		rm -f /quadstorvtl/quadstor.lock
		quadstor_stop
		exit 1
	fi
}

quadstorvtl_start() {

	if [ -f /quadstorvtl/quadstor.lock ]; then
		sleep 60
	fi

	vtmdaemonpid=`/quadstorvtl/bin/pidof /quadstorvtl/sbin/vtmdaemon 2> /dev/null`
	if [ "$vtmdaemonpid" != "" ]; then
		echo "QUADStor VTL Daemon already running..."
		exit 1
	fi
	
        echo -n $"Starting $prog: "

	touch /quadstorvtl/quadstor.lock
	if [ -f /tmp/.s.PGSQL.9989 -o -f /tmp/.s.PGSQL.9989.lock ]; then
		/quadstorvtl/pgsql/etc/pgsql stop > /dev/null 2>&1
	fi

	/quadstorvtl/pgsql/etc/pgsql start
	check_error "Cannot start database"

	/sbin/kldload /quadstorvtl/lib/modules/vtlcore.ko > /dev/null 2>&1
	check_error "Failed to insert core module"

	/sbin/kldload /quadstorvtl/lib/modules/vtldev.ko > /dev/null 2>&1 
	check_error "Failed to insert vtldev module"

	/sbin/kldload /quadstorvtl/lib/modules/iscsit.ko > /dev/null 2>&1
	check_error "Failed to insert iscsi target module"

	daemon /quadstorvtl/sbin/ietd

	export PATH=$PATH:/quadstorvtl/bin
	rm -f /quadstorvtl/.vtmdaemon
	/quadstorvtl/sbin/vtmdaemon > /dev/null 2>&1
	check_error "Cannot start master daemon"

	sleep 5

	/quadstorvtl/bin/scctl -l > /dev/null 2>&1
	rm -f /quadstorvtl/quadstor.lock
}

quadstorvtl_status() {
	vtmdaemonpid=`/quadstorvtl/bin/pidof /quadstorvtl/sbin/vtmdaemon 2> /dev/null`
	ietdpid=`/quadstorvtl/bin/pidof /quadstorvtl/sbin/ietd 2> /dev/null`
	if [ "${vtmdaemonpid}" != "" -o "${ietdpid}" != "" ] ; then 
		echo "QUADStor VTL daemon is running..."
		exit 1
	else
		echo "QUADStor VTL daemon is stopped"
		exit 1
	fi
	
}

load_rc_config $name

: ${quadstorvtl_enable:="NO"}

run_rc_command "$1"

