#!/bin/sh
#
# QUADStor init script 
# chkconfig: 345 84 16
# description: QUADStor Data Protection 
#

# PROVIDE: quadstor
# REQUIRE: DAEMON HOSTNAME mountcritlocal NETWORK
# BEFORE: nfsd
# KEYWORD: nojail shutdown

. /etc/rc.subr
name="quadstor"
start_cmd="quadstor_start"
stop_cmd="quadstor_stop"
status_cmd="quadstor_status"
rcvar=`set_rcvar`

quadstor_stop() {
	if [ -f /quadstorvtl/quadstor.lock ]; then
		echo "Waiting 60 seconds for lock"
		sleep 60
	fi

	touch /quadstorvtl/quadstor.lock

	if [ -f /quadstorvtl/etc/iscsit ]; then
		/quadstorvtl/etc/iscsit stop > /dev/null 2>&1
	fi

	echo -n $"Stopping $prog: "
	/quadstorvtl/bin/scctl -u > /dev/null 2>&1
	sleep 4 

	pkill vtmdaemon
	rm -f /quadstorvtl/.vtmdaemon

	/quadstorvtl/pgsql/etc/pgsql stop

	/sbin/kldunload iscsit > /dev/null 2>&1
	/sbin/kldunload ldev > /dev/null 2>&1
	/sbin/kldunload vtlcore > /dev/null 2>&1
	rm -f /tmp/.quadstortl.* > /dev/null 2>&1
	rm -f /quadstorvtl/quadstor.lock
}

check_error() {
	if [ "$?" != "0" ]; then
		echo "$1"
		rm -f /quadstorvtl/quadstor.lock
		quadstor_stop
		exit 1
	fi
}

quadstor_start() {

	if [ -f /quadstorvtl/quadstor.lock ]; then
		sleep 60
	fi

	vtmdaemonpid=`/quadstorvtl/bin/pidof /quadstorvtl/sbin/vtmdaemon 2> /dev/null`
	if [ "$vtmdaemonpid" != "" ]; then
		echo "QUADStor Daemon already running..."
		exit 1
	fi
	
        echo -n $"Starting $prog: "

	touch /quadstorvtl/quadstor.lock
	if [ -f /tmp/.s.PGSQL.9989 -o -f /tmp/.s.PGSQL.9989.lock ]; then
		/quadstorvtl/pgsql/etc/pgsql stop > /dev/null 2>&1
		sleep 1
		rm -f /tmp/.s.PGSQL.9989*
		sleep 1
	fi

	/quadstorvtl/pgsql/etc/pgsql start
	check_error "Cannot start database"
	sleep 10 

	/sbin/kldload /quadstorvtl/lib/modules/vtlcore.ko > /dev/null 2>&1
	check_error "Failed to insert core module"

	/sbin/kldload /quadstorvtl/lib/modules/ldev.ko > /dev/null 2>&1 
	check_error "Failed to insert ldev module"

	if [ -f /quadstorvtl/lib/modules/iscsit.ko ]; then
		/sbin/kldload /quadstorvtl/lib/modules/iscsit.ko > /dev/null 2>&1
		check_error "Failed to insert iscsi target module"
	fi

	pkill vtmdaemon
	export PATH=$PATH:/quadstorvtl/bin
	/quadstorvtl/sbin/vtmdaemon > /dev/null 2>&1
	check_error "Cannot start master daemon"

	if [ -f /quadstorvtl/lib/modules/iscsit.ko ]; then
		/quadstorvtl/etc/iscsit start
	fi

	sleep 10 
	/quadstorvtl/bin/scctl -l > /dev/null 2>&1
	rm -f /quadstorvtl/quadstor.lock
}

quadstor_status() {
	vtmdaemonpid=`/quadstorvtl/bin/pidof /quadstorvtl/sbin/vtmdaemon 2> /dev/null`
	ietdpid=`/quadstorvtl/bin/pidof /quadstorvtl/sbin/ietd 2> /dev/null`
	if [ "${vtmdaemonpid}" != "" -o "${ietdpid}" != "" ] ; then 
		echo "QUADStor VTL daemon is running..."
		exit 1
	else
		echo "QUADStor VTL daemon is stopped"
		exit 1
	fi
	
}

load_rc_config $name

: ${quadstor_enable:="NO"}

run_rc_command "$1"

