#ifndef QS_RAWDEFS_H_
#define QS_RAWDEFS_H_

#define BLOCK_BLOCKNR_BITS		38	
#define BLOCK_BLOCKNR_MASK		((1ULL << BLOCK_BLOCKNR_BITS) - 1)
/* 44 bits of block */
#define BLOCK_BLOCKNR(block)		((uint64_t)(block & BLOCK_BLOCKNR_MASK))

#define BLOCK_BID_BITS			9
#define BLOCK_BID_MASK			((1ULL << BLOCK_BID_BITS) - 1)	
/* 15 bits of bid */
#define BLOCK_BID(block)		(((uint32_t)((block >> BLOCK_BLOCKNR_BITS) & BLOCK_BID_MASK)))

#define SET_BLOCK(block,blocknr,bid)	(block = ((((uint64_t)(bid)) << BLOCK_BLOCKNR_BITS) | blocknr))

#define BDEV_META_SIZE		LBA_SIZE
#define BINT_INDEX_META_SIZE	LBA_SIZE	

#define INDEX_META_OFFSET_MASTER	(VTAPES_OFFSET + (MAX_VTAPES * LBA_SIZE))
#define INDEX_META_OFFSET_NORMAL	(VTAPES_OFFSET)


#define MAX_UNIT_ATTENTIONS	8
#define STALE_INITIATOR_TIMEOUT	(60 * 60 * 1000) /* 1 hour */
#define INITIATOR_NAME_MAX	256

#define EW_SIZE	(512 * 1024 * 1024)

#define QUADSTOR_MAGIC_BLK_MAP		0x4841

enum {
	NO_ERROR,
	FILEMARK_ENCOUNTERED,
	SETMARK_ENCOUNTERED,
	EOD_REACHED,
	EW_REACHED,
	BOM_REACHED,
	UNDERLENGTH_COND_ENCOUNTERED,
	OVERLENGTH_COND_ENCOUNTERED,
	MEDIA_ERROR,
	INVALID_PARTITION,
	OVERWRITE_WORM_MEDIA,
	VOLUME_OVERFLOW_ENCOUNTERED,
};

#define RMB_MASK		0x80

enum {
	SEGMENT_TYPE_META,
	SEGMENT_TYPE_DATA,
};

#define STALE_INITIATOR_TIMEOUT	(60 * 60 * 1000) /* 1 hour */

#endif
