#ifndef QUADSTOR_SENSE_H_
#define QUADSTOR_SENSE_H_

#define NO_ASC						0x00
#define NO_ASCQ						0x00

#define BUS_RESET_ASC					0x29
#define BUS_RESET_ASCQ					0x00

#define COMMANDS_CLEARED_BY_ANOTHER_INITIATOR_ASC	0x2F
#define COMMANDS_CLEARED_BY_ANOTHER_INITIATOR_ASCQ	0x00

#define INVALID_FIELD_IN_CDB_ASC			0x24
#define INVALID_FIELD_IN_CDB_ASCQ			0x00

#define INVALID_FIELD_IN_PARAMETER_LIST_ASC		0x26
#define INVALID_FIELD_IN_PARAMETER_LIST_ASCQ		0x00

#define INVALID_COMMAND_OPERATION_CODE_ASC		0x20
#define INVALID_COMMAND_OPERATION_CODE_ASCQ		0x00

#define NO_ADDITIONAL_SENSE_INFORMATION_ASC		0x00
#define NO_ADDITIONAL_SENSE_INFORMATION_ASCQ		0x00

#define LOGICAL_UNIT_NOT_READY_CAUSE_NOT_REPORTABLE_ASC		0x04
#define LOGICAL_UNIT_NOT_READY_CAUSE_NOT_REPORTABLE_ASCQ	0x00

#define LOGICAL_UNIT_NOT_READY_INTIALIZING_COMMAND_REQUIRED_ASC		0x04
#define LOGICAL_UNIT_NOT_READY_INTIALIZING_COMMAND_REQUIRED_ASCQ	0x02

#define WRITE_ERROR_ASC				0x0C
#define WRITE_ERROR_ASCQ			0x00

#define FILEMARK_DETECTED_ASC			0x00
#define FILEMARK_DETECTED_ASCQ			0x01

#define SETMARK_DETECTED_ASC			0x00
#define SETMARK_DETECTED_ASCQ			0x03

#define LOGICAL_UNIT_NOT_CONFIGURED_ASC			0x68
#define LOGICAL_UNIT_NOT_CONFIGURED_ASCQ		0x00

#define LOGICAL_UNIT_NOT_SUPPORTED_ASC			0x25
#define LOGICAL_UNIT_NOT_SUPPORTED_ASCQ			0x00

#define MODE_PARAMETERS_CHANGED_ASC			0x2A
#define MODE_PARAMETERS_CHANGED_ASCQ			0x01

#define RESERVATIONS_PREEMPTED_ASC			0x2A
#define RESERVATIONS_PREEMPTED_ASCQ			0x03

#define RESERVATIONS_RELEASED_ASC			0x2A
#define RESERVATIONS_RELEASED_ASCQ			0x04

#define REGISTRATIONS_PREEMPTED_ASC			0x2A
#define REGISTRATIONS_PREEMPTED_ASCQ			0x05

#define LOGICAL_UNIT_IS_IN_PROCESS_OF_BECOMING_READY_ASC	0x04
#define LOGICAL_UNIT_IS_IN_PROCESS_OF_BECOMING_READY_ASCQ	0x01

#define INTERNAL_TARGET_FAILURE_ASC			0x44
#define INTERNAL_TARGET_FAILURE_ASCQ			0x00

#define COMMAND_PHASE_ERROR_ASC				0x4A
#define COMMAND_PHASE_ERROR_ASCQ			0x00

#define PARAMETER_LIST_LENGTH_ERROR_ASC			0x1A 
#define PARAMETER_LIST_LENGTH_ERROR_ASCQ		0x00

#define INVALID_RELEASE_OF_PERSISTENT_RESERVATION_ASC	0x26
#define INVALID_RELEASE_OF_PERSISTENT_RESERVATION_ASCQ	0x04

#define INSUFFICIENT_RESERVATION_RESOURCES_ASC		0x55
#define INSUFFICIENT_RESERVATION_RESOURCES_ASCQ		0x02

#define INSUFFICIENT_REGISTRATION_RESOURCES_ASC		0x55
#define INSUFFICIENT_REGISTRATION_RESOURCES_ASCQ	0x04

#define BUS_RESET_ASC					0x29
#define BUS_RESET_ASCQ					0x00

#define MEDIUM_MAY_HAVE_CHANGED_ASC		0x28
#define MEDIUM_MAY_HAVE_CHANGED_ASCQ		0x00

#define IMPORT_EXPORT_ACCESSED_ASC		0x28
#define IMPORT_EXPORT_ACCESSED_ASCQ		0x01

#define MEDIUM_MAGAZINE_NOT_ACCESSIBLE_ASC	0x3B
#define MEDIUM_MAGAZINE_NOT_ACCESSIBLE_ASCQ	0x11

#define MEDIUM_DESTINATION_ELEMENT_FULL_ASC	0x3B
#define MEDIUM_DESTINATION_ELEMENT_FULL_ASCQ	0x0D

#define MEDIUM_SOURCE_ELEMENT_EMPTY_ASC		0x3B
#define MEDIUM_SOURCE_ELEMENT_EMPTY_ASCQ	0x0E

#define INCOMPATIBLE_MEDIUM_INSTALLED_ASC	0x30
#define INCOMPATIBLE_MEDIUM_INSTALLED_ASCQ	0x00

#define MEDIUM_NOT_PRESENT_ASC			0x3A
#define MEDIUM_NOT_PRESENT_ASCQ			0x00

#define EOM_DETECTED_ASC			0x00
#define EOM_DETECTED_ASCQ			0x02

#define BOM_DETECTED_ASC			0x00
#define BOM_DETECTED_ASCQ			0x04

#define EOD_DETECTED_ASC			0x00
#define EOD_DETECTED_ASCQ			0x05

#define WORM_MEDIUM_OVERWRITE_ATTEMPTED_ASC	0x30
#define WORM_MEDIUM_OVERWRITE_ATTEMPTED_ASCQ	0x0C

#define SEQUENTIAL_POSITIONING_ERROR_ASC	0x3B
#define SEQUENTIAL_POSITIONING_ERROR_ASCQ	0x00

#define MEDIUM_REMOVAL_PREVENTED_ASC		0x53
#define MEDIUM_REMOVAL_PREVENTED_ASCQ		0x02

#define INVALID_ELEMENT_ADDRESS_ASC		0x21
#define INVALID_ELEMENT_ADDRESS_ASCQ		0x01

#define UNLOAD_TAPE_FAILURE_ASC			0x53
#define UNLOAD_TAPE_FAILURE_ASCQ		0x01

#define POSITION_PAST_BEGINNING_OF_MEDIUM_ASC	0x3B
#define POSITION_PAST_BEGINNING_OF_MEDIUM_ASCQ	0x0C

#define PARAMETER_VALUE_INVALID_ASC		0x26
#define PARAMETER_VALUE_INVALID_ASCQ		0x02

#define AUXILIARY_MEMORY_READ_ERROR_ASC		0x11
#define AUXILIARY_MEMORY_READ_ERROR_ASCQ	0x12

#define AUXILIARY_MEMORY_WRITE_ERROR_ASC	0x0C
#define AUXILIARY_MEMORY_WRITE_ERROR_ASCQ	0x0B

#define SAVING_PARAMETERS_NOT_SUPPORTED_ASC	0x39
#define SAVING_PARAMETERS_NOT_SUPPORTED_ASCQ	0x00

#endif /* SENSE_H_ */
