/*
 * vendor ids
 */
#ifndef VTL_VENDOR_H_
#define VTL_VENDOR_H_

#define VENDOR_OUI_QUADSTOR	0xEEF0FF
#define VENDOR_ID_QUADSTOR	"QUADSTOR"
#define VENDOR_ID_QUANTUM	"QUANTUM "
#define VENDOR_ID_ATL		"ATL     "
#define VENDOR_ID_IBM		"IBM     "
#define VENDOR_ID_HP		"HP      "
#define VENDOR_ID_COMPAQ	"COMPAQ  "
#define VENDOR_ID_ADIC		"ADIC    "
#define VENDOR_ID_OVERLAND	"OVERLAND"

#define PRODUCT_ID_QUADSTOR		"QUADSTORP"
#define PRODUCT_ID_QUADSTOR_FCBRIDGE	"FCSCBRIDGE"
#define PRODUCT_ID_IBM_ULT1		"ULTRIUM-TD1"
#define PRODUCT_ID_IBM_ULT2		"ULTRIUM-TD2"
#define PRODUCT_ID_IBM_ULT3		"ULTRIUM-TD3"
#define PRODUCT_ID_IBM_ULT4		"ULTRIUM-TD4"
#define PRODUCT_ID_IBM_ULT5		"ULTRIUM-TD5"
#define PRODUCT_ID_IBM_ULT6		"ULTRIUM-TD6"
#define PRODUCT_ID_IBM_ULT1_ALT		"ULT3580-TD1"
#define PRODUCT_ID_IBM_ULT2_ALT		"ULT3580-TD2"
#define PRODUCT_ID_IBM_ULT3_ALT		"ULT3580-TD3"
#define PRODUCT_ID_IBM_ULT3_HH		"ULT3580-HH3"
#define PRODUCT_ID_IBM_ULT4_ALT		"ULT3580-TD4"
#define PRODUCT_ID_IBM_ULT5_ALT		"ULT3580-TD5"
#define PRODUCT_ID_IBM_ULT6_ALT		"ULT3580-TD6"
#define PRODUCT_ID_SDLT320		"SDLT320"
#define PRODUCT_ID_SDLT600		"SDLT600"
#define PRODUCT_ID_SDLT220		"SuperDLT1"
#define PRODUCT_ID_HP_VS80		"DLT VS80"
#define PRODUCT_ID_HP_VS160		"DLT VS160"
#define PRODUCT_ID_HP_SDLT1		"SDLT1"
#define PRODUCT_ID_HP_ULT1		"Ultrium 1-SCSI"
#define PRODUCT_ID_HP_ULT2		"Ultrium 2-SCSI"
#define PRODUCT_ID_HP_ULT3		"Ultrium 3-SCSI"
#define PRODUCT_ID_HP_ULT4		"Ultrium 4-SCSI"
#define PRODUCT_ID_HP_ULT5		"Ultrium 5-SCSI"
#define PRODUCT_ID_HP_ULT6		"Ultrium 6-SCSI"
#define PRODUCT_ID_VIBM_3583		"ULT3583-TL"
#define PRODUCT_ID_VIBM_3584_PREFIX	"03584L"
#define PRODUCT_ID_VIBM_3584		"03584L32"
#define PRODUCT_ID_VIBM_3584_2		"03584L42"
#define PRODUCT_ID_VIBM_TS3100		"3573-TL"
#define PRODUCT_ID_VQUANTUM_M2500	"2500"
#define PRODUCT_ID_VADIC_SCALAR24	"Scalar 24"
#define PRODUCT_ID_VADIC_SCALAR100	"Scalar 100"
#define PRODUCT_ID_VADIC_SCALARi2000	"Scalar i2000"
#define PRODUCT_ID_VHP_EMLSERIES	"EML E-Series"
#define PRODUCT_ID_VHP_ESLSERIES	"ESL E-Series"
#define PRODUCT_ID_VHP_ESL9000		"ESL9000 Series"
#define PRODUCT_ID_VHP_MSLSERIES	"MSL G3 Series"
#define PRODUCT_ID_VHP_MSL6000		"MSL6000 Series"
#define PRODUCT_ID_VOVL_NEOSERIES	"NEO Series"
#define VHP_EMLESERIES_ID_INCR		10


#define PRODUCT_REVISION_QUADSTOR	"6.24"
#define PRODUCT_REVISION_FULL		"6.24.0002"
#define PRODUCT_REVISION_SDLT220	"1.00"
#define PRODUCT_REVISION_SDLT320	"1.00"
#define PRODUCT_REVISION_3584		"1.00 "
#define PRODUCT_REVISION_M2500		"1.00"
#define PRODUCT_REVISION_3580		"1.00"
#define PRODUCT_REVISION_TS3100		"4.40"
#define PRODUCT_REVISION_IBM_ULT3	"64D2"
#define PRODUCT_REVISION_IBM_LTFS	"B170"
#define PRODUCT_REVISION_NEO		"1.00"

#define DENSITY_ULTRIUM_1		0x40
#define DENSITY_ULTRIUM_2		0x42
#define DENSITY_ULTRIUM_3		0x44
#define DENSITY_ULTRIUM_4		0x46
#define DENSITY_ULTRIUM_5		0x58
#define DENSITY_ULTRIUM_6		0x5A

#define DENSITY_DLT_4_DEFAULT				0x40
#define DENSITY_SUPER_DLT_1_DEFAULT			0x48
#define DENSITY_SUPER_DLT_2_DEFAULT			0x49
#define DENSITY_VSTAPE_DEFAULT				0x50
#define DENSITY_SUPER_DLT_3_DEFAULT			0x4A
#define DENSITY_SUPER_DLT_1_MODE_COMPRESSED		0x90
#define DENSITY_SUPER_DLT_1_MODE_UNCOMPRESSED 		0x91
#define DENSITY_SUPER_DLT_2_MODE_COMPRESSED		0x92
#define DENSITY_SUPER_DLT_2_MODE_UNCOMPRESSED 		0x93

#define MEDIUM_TYPE_DLT_4		0x85
#define MEDIUM_TYPE_SDLT_1		0x86
#define MEDIUM_TYPE_SDLT_2		0x87
#define MEDIUM_TYPE_VSTAPE		0x90
#define MEDIUM_TYPE_LTO_1		0x18
#define MEDIUM_TYPE_LTO_2		0x28
#define MEDIUM_TYPE_LTO_3		0x38
#define MEDIUM_TYPE_LTO_4		0x48
#define MEDIUM_TYPE_LTO_5		0x58
#define MEDIUM_TYPE_LTO_6		0x68
#define MEDIUM_TYPE_LTO_1_WORM		0x1C /* ??? */
#define MEDIUM_TYPE_LTO_2_WORM		0x2C /* ??? */
#define MEDIUM_TYPE_LTO_3_WORM		0x3C
#define MEDIUM_TYPE_LTO_4_WORM		0x4C
#define MEDIUM_TYPE_LTO_5_WORM		0x5C
#define MEDIUM_TYPE_LTO_6_WORM		0x6C

#endif
