KMOD = iscsit

SRCS = vnode_if.h opt_cam.h tio.c iscsi.c nthread.c config.c crc32c.c digest.c conn.c session.c target.c param.c scdefs.c eventbsd.c

QUADSTOR_ROOT= /quadstorvtl/quadstor/

CFLAGS= -I$(QUADSTOR_ROOT)/export -I../include/ -DFREEBSD
CFLAGS += -O2
#DEBUG_FLAGS = -g

.include <bsd.kmod.mk>
