ALTER TABLE FCCONFIG ADD COLUMN WWPN1 VARCHAR(40) default NULL;
ALTER TABLE PHYSSTOR ADD COLUMN GROUPID INT default 0;
ALTER TABLE VCARTRIDGE DROP COLUMN TAPEID;
ALTER TABLE VCARTRIDGE DROP COLUMN VSTATUS;
