#! /bin/sh

# PostgreSQL boot time startup script for FreeBSD.  Copy this file to
# /usr/local/etc/rc.d/postgresql.

# Created through merger of the Linux start script by Ryan Kirkpatrick
# and the script in the FreeBSD ports collection.

# $PostgreSQL: pgsql/contrib/start-scripts/freebsd,v 1.4 2004/10/01 18:30:21 tgl Exp $

## EDIT FROM HERE

# Installation prefix
prefix=/quadstorvtl/pgsql

# Data directory
PGDATA="/quadstorvtl/pgsql/data"

# Who to run the postmaster as, usually "postgres".  (NOT "root")
PGUSER=vtdbuser

# Where to keep a log file
PGLOG="$PGDATA/serverlog"

## STOP EDITING HERE

# The path that is to be used for the script
PATH=/quadstorvtl/bin:/quadstorvtl/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# What to use to start up the postmaster (we do NOT use pg_ctl for this,
# as it adds no value and can cause the postmaster to misrecognize a stale
# lock file)
DAEMON="$prefix/bin/postmaster"

# What to use to shut down the postmaster
PGCTL="$prefix/bin/pg_ctl"

# Only start if we can find the postmaster.
test -x "$DAEMON" || exit 0

if [ -x /sbin/runuser ]
then
    SU=/sbin/runuser
else
    SU=su
fi

case $1 in
    start)
	rm -f /quadstorvtl/pgsql/data/postmaster.pid
	rm -f /quadstorvtl/pgsql/pg.log
	touch /quadstorvtl/pgsql/pg.log
	chown vtdbuser:vtdbuser /quadstorvtl/pgsql/pg.log
	$SU -l $PGUSER -c "$PGCTL start -w -D '$PGDATA' -l /quadstorvtl/pgsql/pg.log > /dev/null 2>&1"
	;;
    stop)
	$SU -l $PGUSER -c "$PGCTL stop -w -D '$PGDATA' -s -m fast > /dev/null 2>&1"
	pkill -f /quadstorvtl/pgsql/bin/postmaster > /dev/null 2>&1
	pkill -f /quadstorvtl/pgsql/bin/postgres > /dev/null 2>&1
	rm -f /var/run/postmaster.9989.pid > /dev/null 2>&1
	rm -f /quadstorvtl/pgsql/data/postmaster.pid > /dev/null 2>&1
	rm -f /var/lock/subsys/pgsql > /dev/null 2>&1
	rm -f /tmp/.s.PGSQL.9989* > /dev/null 2>&1
	;;
    restart)
    	stop
	start
	;;
    status)
	$SU -l $PGUSER -c "$PGCTL status -D '$PGDATA'"
	;;
    *)
	# Print help
	echo "Usage: `basename $0` {start|stop|restart|status}" 1>&2
	exit 1
	;;
esac

exit 0
